### ISSUE TITLE
canvas2svg error

### ISSUE THREAD

**Issue by joshsadam** [phylocanvas/phylocanvas-plugin-export-svg#1]
Hi @richardgoater 

Thanks for posting this so quickly.  I thought canvas2svg might be the way to accomplish it.  I cloned the repo and tried to run it with our demo code, but I am running into some difficulty.  I am getting the following error: 

```
canvas2svg.js?3dac:531 Uncaught Error: Attempted to apply path command to node g
```

Any thoughts?

Thanks,
Josh

**Comment by kabudahab** [comment]
It seems that we need some modifications to core Phylocanvas drawing methods to get it to work. if you run from your phylocanvas-plugin-export-svg
 clone `npm install github:phylocanvas/phylocanvas#export-svg-changes`, then you can switch to this Phylocanvas branch which contains some changes to get rid of the above error. However, the generated SVG does not look promising.

**Comment by joshsadam** [comment]
Thanks for fixing this one.  This is really coming along well.
